---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-kactus
  name: vmi-kactus
spec:
  domain:
    cpu:
      cores: 2
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: default
      - bridge: {}
        name: aux-net
        macAddress: 62:b5:00:ed:3e:01 # in the VM
      rng: {}
    resources:
      requests:
        memory: 1024M
  networks:
  - pod:
      pod: {}
    name: default
  - kactus:
      networkName: bridge-conf
    name: aux-net
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/fedora-with-test-tooling-container-disk:devel
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
        ssh_pwauth: True
    name: cloudinitdisk
